sabotage-linux/sabotage

pkg/audacity

Audacity was failing to build because it don't support actual version of ffmpeg. So disabling ffmpeg support prevent the error.

disabled ffmpeg on audacity to solve compilation problems

---

pkg/wayland

I've had some trouble building with ZSH as default shell. Added a new wiki page with instructions how to avoid this: https://github.com/sabotage-linux/sabotage/wiki/ZSH

wayland bump to 1.7.0

---

pkg/stage1

This change shaves 12.1MB from the resulting stage1 build, a bit over an 8% savings.

stage1: Clean up bootstrap compiler and libc.

---

build-stage0

A user reported failure running build-stage0 against a pre-existing directory used for SABOTAGE_BUILDDIR. We now test for '/bin' being present under the assumption that if it is missing, likely the directory needs to be initialized.

build-stage0: Initialize SABOTAGE_BUILDDIR if it exists, but is empty.

---

pkg/libressl

fixes CVE-2015-5333 and CVE-2015-5334
http://www.openwall.com/lists/oss-security/2015/10/16/1

bump libressl to 2.2.4

---

pkg/stage0_musl

./build-stage0 fails due to a missing "$" in pkg/stage0_musl.
This pull request fixes that little typo.

pkg/stage0_musl: fix typo

---

KEEP/rsync-fix-proto.h-tstamp-target.patch
pkg/rsync

rsync build fails with the following error if perl isn't available.
```
perl ./mkproto.pl ./*.c ./lib/compat.c
/bin/sh: perl: not found
make: *** [proto.h-tstamp] Error 127
```
Created a patch with the change noted here: https://lists.samba.org/archive/rsync/2015-November/030439.html

rsync: add patch to remove dependency on perl

---

pkg/libtorrent
pkg/rtorrent

This pull request bumps both libtorrent and rtorrent to the latest version. I've changed the execinfo.h test removal according the new configure files.

bump libtorrent and rtorrent

---

pkg/b2sum

Tarball size: 68124710 (68.125MB)
$ time sha512sum otp_src_18.0.tar.gz
84ec2a3834270c1babe153572d6187faa36c12128e604037d55be01719788c0dd79d46769ea7090d530b746206a25fe02346b02849abee10ee41ed4ac7567c02  otp_src_18.0.tar.gz
0m0.32s real     0m0.00s user     0m0.00s system
$ time b2sum otp_src_18.0.tar.gz
fee70f49921c4fe3e38ae4f16b3491e51866ecf57a9e954c4bd5f0ec446604de3fa972fd1a8452acc73d6eaa3041ea2b738a694944af22da5b4352e8117dbfcf  otp_src_18.0.tar.gz
0m0.10s real     0m0.00s user     0m0.00s system
Time recorded on a Xeon E3-1240v3 with an Intel 530 Series SSD.
See https://blake2.net/ for further details.

Adding b2sum: A sum utility for the BLAKE2 cryptohash function.

---

pkg/su

The su binary will be moved to $butch_install_dir$butch_prefix/bin/su
and symlinked from there, instead of directly moved to /bin/su.

su: install to $butch_install_dir instead of /bin

---

pkg/libtorrent

This reduces the size from 15.3mb to 1.6mb.

libtorrent: disable debug information

---

pkg/stage1

gcc3 and stage0-musl should get removed by installing stage1.
the cleanup never happens, because there is no stage0 directory.
this commit rewrites the check from stage0 to stage0-musl.

stage1: fix stage0 cleanup

---

KEEP/initramfs.sh
pkg/initramfs

This adds an initrd-style pre-userspace to be included in the bootloader
configuration. This is useful when your rootfs requires user-space actions
before being available. Examples:
- lvm logical volumes (lvm)
- encrypted partitions (cryptsetup)
- squashfs rootfs
Step-by-step instruction for usage:
- Install lvm or cryptsetup (or both), depending on your disk structure
- Rebuild the initramfs so the executables get included
- The initramfs is placed as /boot/initrd.img. Add it to your extlinux
boot configuration with "`INITRD initrd.img`"
- Use the kernel options from below to your extlinux config like this:
"`APPEND cryptsetup=/dev/sda2:cryptroot root=/dev/mapper/cryptroot`"
The kernel options as defined in bootparam(7) still apply. You are
encouraged to read that manpage first. The …

add initramfs:

---

pkg/scrot
pkg/scrot-debian-patches

This adds debian's ```-u, --focused``` option to scrot, which allows it to capture the focused window.

scrot: add debian's focused window patch

---

KEEP/gcc-474-gperf.patch
pkg/gcc474

https://gcc.gnu.org/ml/gcc-patches/2015-08/msg00375.html
not sure how many people still use gcc474, but I happened to be messing around with java JNI bindings and had to fix this package to get gcj and javac

gcc474: fix compile error on newer gperf versions

---

pkg/firefox

there was a spelling mistake (FFIDR) that prevented the wrapper script from working
also, I've added command line args so you can call ```firefox https://...``` and it will work

Firefox wrapper script fixes

---

KEEP/qtwebkit-5.9.0-icu_59-1.patch
pkg/qt5

the latest icu update broke qt5 apps due to symbol changes, so I tried recompiling qt5 against the updated icu and ran into errors.
this patch from linux from scratch fixes the compile errors

qt5: add patch for icu59

---

pkg/wine-staging
pkg/wine-staging-patches

the latest steam update broke steam on wine due to WSAIoctl returning invalid size for some value https://bugs.winehq.org/show_bug.cgi?id=43315
version 2.13 fixes this issue

wine-staging: bump to 2.13

---

KEEP/super_chroot.c

user_namespaces(7) states that the setgroups(2) syscall must be
explicitly disabled for an following write to the gid_map to succeed.
Before this commit, these writes failed silently with EPERM.

Fix gid_map for super_chroot

---

enter-chroot

This makes the invocation of enter-chroot be like that of regular chroot.

Remove /bin/sh from enter-chroot invocation

---

README.md
utils/optimize-chroot.sh
utils/rebuild-stage1.sh

After a conversation with @rofl0r, it appears that `optimize-chroot.sh` could be used as a more general step for reproducible builds. The script has also been renamed to be more generic about its purpose, as it is no longer just for optimization reasons.
The order of the packages mirror the order they are built during stage0 -> stage1. Everything that involves a C compiler in stage0/stage1 has now been included.
Added:
* sabotage-core
* kbd
* man
* ca-certificates
The necessity of all of these packages being rebuilt should probably be debated, but there's no harm including them either.

Updating and repurposing optimize-chroot.sh

---

pkg/zsh

zsh attempts to run the autoheader command as part of its Makefile.
this makes autoconf a dependency of zsh.
however, this command doesn't actually seem to *do* anything
besides dump a few files in autom4te.cache, so it's safe to delete it.

zsh: relieve dependency on autoconf

---

KEEP/python3-dont_write_bytecode.patch
KEEP/python3-pathsearch.patch
KEEP/python3-sysconfig-prefix.patch
KEEP/python3-xcompile.patch
pkg/python3

as requested, but there are a few things to consider before merging:
* no cross-compilation support (the big one)
* no .pyo patch (pretty minor)
* <strike>no alternate mirror (easy fix)</strike>
the build script and patches largely match those of the python2 package, so credits to its author. a couple lines were also borrowed from Arch Linux's package to make various scripts invoke python3 instead of defaulting to python2.

add Python 3 package

---

pkg/libblkid

The recent musl release has removed <sys/sysmacros.h> from being included via
<sys/types.h>. This has resulted in libblkid silently failing to build, which
is not detected until e2fsprogs fails to build.

libblkid: Fixing stage1 breakage.

---

KEEP/__stack_chk_fail_local.c
pkg/fte
pkg/libsodium
pkg/musl
pkg/python
pkg/python-lxml
pkg/python-twisted

* musl: fix ssp on i?86
* python: add sqlite dep.
* libsodium: add patch
* python-twisted: bump to 19.2.1
* fte: fix sha512

fix ssp, bumps and libsodium

---

pkg/libsodium
pkg/popt
pkg/python-pyasn1
pkg/python-six

python-pyasn1: bump to 0.4.6
python-six: bump to 1.12.0
popt: add secondary mirror (current returns host not found)
libsodium: fix filesize and sha512

Bumps and fixes

---

KEEP/syslinux6-ext4_fix_64bit_feature.patch
pkg/gnutls
pkg/libtasn1
pkg/syslinux6

Couple of package updates. Build tested including some packages that depend on gnutls.
These updates include important fixes for x86:
- gnutls 3.6.9 had a bug that broke build on x86
- syslinux6 was unable to boot when installed on partition with ext4 filesystem having 64bit feature enabled (default when creating ext4 filesystem).

Bump gnutls, libtasn1 and syslinux6

---

pkg/zig

Straight forward to port other than the hour it takes to compile on a Ryzen 7 3700X running eight threads.

Adding zig 0.7.1

---

KEEP/cmake-isystem.patch
KEEP/cmake-lib64.patch
pkg/cmake
pkg/zig

A cmake update was required in order to update the zig recipe.

Zig: Bump to 0.8.0.

---

KEEP/etc/rc.local
KEEP/llvm36-compiler-rt.patch
pkg/clang36
pkg/compiler-rt36
pkg/ffmpeg
pkg/libdrm
pkg/libva
pkg/libva-utils
pkg/llvm-clang36
pkg/python-mako
pkg/xf86-video-ati
pkg/xf86-video-nouveau

I didn't add libva and libva-utils to world because I didn't test cross compiling. Otherwise its all tested on real hardware, including hardware accelerated video via va-api on radeon 5000 and 7000 series cards, and RX480. I'm working on mesa update and some amdgpu bits so it would be great if you could merge these.

Couple of bumps, fixes and adds

---

pkg/intel-gmmlib
pkg/intel-media-driver
pkg/intel-vaapi-driver
pkg/intel-vaapi-driver-g45
pkg/intel-vaapi-driver-std

These are only build tested (native x86_64) as I lack the hardware at the moment to try these out. Commit messages should give some idea which one supports what but I will of course update wiki if these get merged.
I also included a meta package. Even though it might not have been necessary, it's there now in case packages in future need to depend on Intel vaapi.

Intel VA-API drivers

---

pkg/busybox

This just copies all of the make flags to the `allnoconfig` step too. I needed this because if `HOSTCC` isn't specified, it defaults to `gcc` and hence errors out if that can't be found in the host system's path when it tries to compile kconfig during the stage0 bootstrap.

busybox: Pass HOSTCC to make allnoconfig

---

KEEP/butch_template_configure_cached.txt
pkg/busybox
pkg/kernel-headers
utils/clean-stage1.sh
utils/rebuild-stage1.sh

@rofl0r This should resolve those issues you noticed with the bootsh bootstrap producing different checksums to the normal bootstrap path. I ran both through to rebuild-stage1, and confirmed with diffoscope that the `/opt` directories of each are identical now.

Resolve reproducible build issues
