sabotage-linux/sabotage

- pkg/protobuf-c
- pkg/uncrustify
Hello,
As i needed them i Added them on my fork, so I you are interested in them, pleas fell free to merge this PR.
Cheers,
Floreal
> Added two packages: protobuf-c and uncrustify

- pkg/libxmp
- pkg/xmp
One of the more versatile and compatible chiptune players around. Also fairly lightweight.
Sorry for that other pull request.
> Add libxmp, xmp

- pkg/ffmpeg
- pkg/lua
- pkg/mksh
- pkg/mpg123
This set of commits is cleaned up.
> ffmpeg, lua, mpg123, mksh: updates and fixes

- KEEP/xorg-server-musl-arm.patch
- pkg/eina
- pkg/evas
- pkg/evas_generic_loaders
- pkg/gegl
- pkg/libraw
- pkg/libxft
- pkg/nasm
- pkg/pixman
- pkg/tzdata
- pkg/xclock
- pkg/xkeyboard-config
- pkg/xorg-server
fixes support for new freetype by updating some of the depending packages (the rest compile fine), also fixes more x-compile issues
> More patches

- pkg/gnupg
- pkg/libgcrypt
https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000395.html
> package updates related to CVE-2016-6316

- KEEP/lvm2-stdio.patch
- pkg/lvm
thanks to Alpine Linux for the new patch
> lvm: bump to 2.02.166

- pkg/daemontools
Just found this in my current checkout. Compiles, but not cross.
> add daemontools

- pkg/digimend
- pkg/xinput
these are very useful drivers that make a lot of graphic tablets just work, I'm using them with my huion h420
also added xinput, which is used to configure area, map tablet to a specific monitor, and so on
> add digimend kernel drivers

- pkg/go
> Upgrade to go 1.8.1

- pkg/xterm
Currently the download of xterm times out!
> Fix xterm download link

- pkg/libutf
> add libutf

- KEEP/services/nginx
- KEEP/services/unbound
- pkg/nginx
- pkg/tinc
- pkg/unbound
* unbound: fix missing dependency (expat); provide runit file; bump to 1.9.2
* nginx: provide runit file; bump to 1.17.1
* tinc: bump to 1.0.35
> Unbound, nginx and tinc

- KEEP/services/ngircd
- KEEP/services/perl5-FCGI-Daemon
- pkg/cgit
- pkg/git218-tarball
- pkg/gitweb
- pkg/ngircd
- pkg/perl5-BSD-Resource
- pkg/perl5-CGI
- pkg/perl5-FCGI
- pkg/perl5-FCGI-Daemon
- pkg/perl5-FCGI-ProcManager
- pkg/perl5-HTML-Parser
* add ngircd, gitweb and multiple perl5 modules
* bump perl5-HTML-Parser to 3.72
> new pkgs, bump

- pkg/extlinux
- pkg/strace
- pkg/xorg-server
More fallout from the musl update.
> Fixing 'core' packages. 

- KEEP/calcurse_initscr.patch
- pkg/calcurse
- pkg/lxc
- pkg/mtr
- pkg/ngircd
* add calcurses and mtr
* lxc: include sys/sysmacros.h
> add pkgs, fix lxc

- pkg/git
- pkg/gitweb
- pkg/nginx
- pkg/python
- pkg/python-pip
- pkg/python-setuptools
- pkg/python-twisted
git, gitweb, python, python-twisted, python-pip, python-setuptools, nginx
> Nobrainer - multiple bumps

- pkg/libjpeg
libjpeg's tarball changed again
> libjpeg: updated tarball again

- pkg/dmenu
- pkg/twm
- pkg/xrdb
- pkg/xterm
> bump some more packages

- pkg/libxcomposite
- pkg/transset
- pkg/xcompmgr
- pkg/xtermcontrol
libxcomposite (bump)
xcompmgr (add)
transset (add)
> bump/add pkgs (libxcomposite, xcompmgr, transset)

- pkg/bspwm
- pkg/libcap-ng
- pkg/libconfig
- pkg/libtasn1
- pkg/rdesktop
- pkg/sxhkd
- pkg/xinput
- pkg/yt-dlp
bumps: libtasn1, xinput, sxhkd, yt-dlp, libconfig
add: rdesktop, bspwm, libcap-ng
> bumps and add
